<section id="devices-bulk-page" aria-label="<?= h($title); ?>">
  <?php if (($pageRequest['saved'] ?? '') === '1'): ?><div class="alert alert-success" role="status"><?= h($L('Device_bulkEditor_savebox_title','Changes saved')); ?></div><?php endif; ?>
  <div class="d-flex justify-content-end mb-3"><a href="devices.php?scansource=<?= rawurlencode($SCANSOURCE); ?>" class="btn btn-success"><?= h($L('Device_bulkEditor_mode_quit','Quit bulk editor')); ?></a></div>
  <form method="post" action="devices.php?scansource=<?= rawurlencode($SCANSOURCE); ?>" id="bulkEditForm">
    <input type="hidden" name="mod" value="bulkedit"><input type="hidden" name="savedata" value="yes"><input type="hidden" name="_csrf" value="<?= h(pialert_csrf_token()); ?>">
    <section class="card mb-3"><div class="card-header"><h2 class="card-title"><?= h($L('Device_bulkEditor_inputbox_title','Bulk fields')); ?></h2></div><div class="card-body"><div class="row g-3">
    <?php foreach (array('owner'=>$L('DevDetail_MainInfo_Owner','Owner'),'type'=>$L('DevDetail_MainInfo_Type','Type'),'group'=>$L('DevDetail_MainInfo_Group','Group'),'location'=>$L('DevDetail_MainInfo_Location','Location'),'comments'=>$L('DevDetail_MainInfo_Comments','Comments'),'connectiontype'=>$L('DevDetail_MainInfo_Network_ConnectType','Connection type'),'linkspeed'=>$L('DevDetail_MainInfo_Network_LinkSpeed','Link speed')) as $field=>$label): ?>
      <div class="col-md-6"><div class="pialert-bulk-field"><div class="form-check"><input class="form-check-input bulk-enable" type="checkbox" id="en_bulk_<?= h($field); ?>" name="en_bulk_<?= h($field); ?>" data-bulk-target="bulk_<?= h($field); ?>"><label class="form-check-label fw-semibold" for="en_bulk_<?= h($field); ?>"><?= h(pialert_v4_ui_plain_label($label)); ?></label></div><?php if ($field === 'comments'): ?><textarea class="form-control mt-2" rows="2" id="bulk_comments" name="bulk_comments" disabled></textarea><?php else: ?><input class="form-control mt-2" type="text" id="bulk_<?= h($field); ?>" name="bulk_<?= h($field); ?>" disabled><?php endif; ?></div></div>
    <?php endforeach; ?>
    <?php foreach (array('AlertAllEvents'=>$L('DevDetail_EveandAl_AlertAllEvents','Alert all events'),'AlertDown'=>$L('DevDetail_EveandAl_AlertDown','Alert down'),'NewDevice'=>$L('DevDetail_EveandAl_NewDevice','New device'),'Archived'=>$L('DevDetail_EveandAl_Archived','Archived'),'PresencePage'=>$L('DevDetail_MainInfo_ShowPresence','Show presence'),'MQTTDevice'=>$L('DevDetail_MainInfo_MQTTDevice','MQTT device')) as $field=>$label): ?>
      <div class="col-md-6"><div class="pialert-bulk-field d-flex align-items-center justify-content-between gap-3"><div class="form-check"><input class="form-check-input bulk-enable" type="checkbox" id="en_bulk_<?= h($field); ?>" name="en_bulk_<?= h($field); ?>" data-bulk-target="bulk_<?= h($field); ?>"><label class="form-check-label fw-semibold" for="en_bulk_<?= h($field); ?>"><?= h($label); ?></label></div><input class="form-check-input bulk-value" type="checkbox" id="bulk_<?= h($field); ?>" name="bulk_<?= h($field); ?>" disabled aria-label="<?= h($label); ?>"></div></div>
    <?php endforeach; ?>
    </div><div class="d-flex flex-wrap gap-2 justify-content-between mt-3"><button type="button" class="btn btn-danger" id="btnBulkDeletion"><?= h($L('Device_bulkDel_button','Delete selected')); ?></button><button type="submit" class="btn btn-warning"><?= h($L('Gen_Save','Save')); ?></button></div></div></section>

    <section class="card"><div class="card-header"><h2 class="card-title"><?= h($L('Device_bulkEditor_hostbox_title','Devices')); ?></h2></div><div class="card-body">
      <div class="d-flex flex-wrap gap-2 justify-content-center mb-3"><button type="button" class="btn btn-success bulk-visibility" data-bulk-class="bulked_offline_border"><?= h($L('WEBS_Page_down','Offline') . ' ' . $L('Gen_show','show') . '/' . $L('Gen_hide','hide')); ?></button><button type="button" class="btn btn-secondary bulk-visibility" data-bulk-class="bulked_online_border"><?= h($L('ICMPMonitor_Shortcut_Online','Online') . ' ' . $L('Gen_show','show') . '/' . $L('Gen_hide','hide')); ?></button><button type="button" class="btn btn-warning" id="bulkOnlyNew"><?= h($labels['newDevices']); ?></button></div>
      <label class="visually-hidden" for="deviceSearch"><?= h($L('EVE_Searchbox','Search')); ?></label><input type="search" class="form-control mx-auto mb-3" id="deviceSearch" placeholder="<?= h($L('EVE_Searchbox','Search') . '…'); ?>">
      <div class="pialert-bulk-device-grid">
      <?php $results = db_execute_prepared($db, 'SELECT dev_Name, dev_MAC, dev_PresentLastScan, dev_Archived, dev_NewDevice, dev_AlertEvents, dev_AlertDeviceDown, dev_PresencePage, dev_MQTTDevice FROM Devices WHERE dev_ScanSource = :scan_source ORDER BY dev_Name COLLATE NOCASE ASC', array(':scan_source' => (string) $SCANSOURCE)); while ($row = $results->fetchArray()):
        $border=$row[2]==1?'bulked_online_border':'bulked_offline_border'; $box=$row[3]==1?'bulked_arc_dev':($row[4]==1?'bulked_new_dev':'bulked_default_dev'); $text=($row[5]==1&&$row[6]==1)?'bulked_checkbox_label_alldown':($row[5]==1?'bulked_checkbox_label_all':($row[6]==1?'bulked_checkbox_label_down':'')); $underline=$row[7]==0?'presence-underlined':''; $hostId='host-'.hash('sha256',(string)$row[1]); ?>
        <div class="bulked_dev_box <?= h($border . ' ' . $box); ?>"><input class="form-check-input hostselection" id="<?= h($hostId); ?>" name="<?= h(str_replace(' ', '_', $row[1])); ?>" type="checkbox" data-host-id="<?= h($row[1]); ?>"><label class="<?= h(trim($text . ' ' . $underline)); ?>" for="<?= h($hostId); ?>"><?= h($row[0]); ?></label><?php if ($row[8] == 1 || $row[7] == 1): ?><span class="pialert-bulk-indicators"><?php if ($row[8] == 1): ?><span class="pialert-bulk-indicator pialert-bulk-indicator-mqtt" role="img" aria-label="<?= h($L('DevDetail_MainInfo_MQTTDevice','MQTT device')); ?>" title="<?= h($L('DevDetail_MainInfo_MQTTDevice','MQTT device')); ?>"><span class="pialert-bulk-mqtt-icon" aria-hidden="true"></span></span><?php endif; ?><?php if ($row[7] == 1): ?><span class="pialert-bulk-indicator pialert-bulk-indicator-presence" role="img" aria-label="<?= h($L('DevDetail_MainInfo_ShowPresence','Show presence')); ?>" title="<?= h($L('DevDetail_MainInfo_ShowPresence','Show presence')); ?>"><i class="fa-regular fa-calendar" aria-hidden="true"></i></span><?php endif; ?></span><?php endif; ?></div>
      <?php endwhile; ?>
      </div><div class="d-flex flex-wrap gap-2 justify-content-end mt-3"><button type="button" class="btn btn-warning" id="bulkVisibleToggle"><?= h($labels['selectVisible']); ?></button><button type="button" class="btn btn-warning" id="bulked_checkall"><?= h($labels['selectAll']); ?></button></div>
    </div></section>
  </form>
</section>
